[Settings]
cacheCleanInterval=10
cacheSizeLimit=10
computerName=hellbox
deleteConfirmThreshold=500
disableVerifyCert=false
kMigrateStatus=true
lastOpenSyncDialogTimestamp=1764590824
maxDownloadRatio=0
maxUploadRatio=0
notifySync=true
syncExtraTempFile=false

[UsedServerAddresses]
main=https://seafile.crits.foo
