[user]
name = "Rob Bailey (actioninja)"
email = "actioninja@criticalaction.net"

[ui]
diff-editor = "meld"
merge-editor = "meld"

[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
