[user]
name = "Rob Bailey (actioninja)"
email = "actioninja@criticalaction.net"

[ui]
diff-editor = "meld-3"

[core]
fsmonitor = "watchman"

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
