[build]
rustc-wrapper = "/usr/bin/sccache"
target-dir = "/var/cache/cargo"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [ "-C", "link-arg=-fuse-ld=/usr/bin/mold" ]

[profile.dev.package."*"]
debug = false
opt-level = 3
